// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chhxqqdixvwbwpvcuupi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoaHhxcWRpeHZ3YndwdmN1dXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MDc2NDIsImV4cCI6MjA1MzI4MzY0Mn0.6Sr0PwCdzUuQO0Z0otSN7mHJGjRuyw4x0J77IE12c2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);